name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Google Cloud Platform (GCP) CLI - gcloud
        uses: actions-hub/gcloud@272.0.0
        with:
          # Project id
          PROJECT_ID: ""
          # GCP authorization credentials
          APPLICATION_CREDENTIALS: ""
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
