name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Google Cloud Platform (GCP) CLI - gcloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/gcloud@272.0.0
        env:
          # Project id
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          # GCP authorization credentials
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          CLI: gcloud 
        with:
          args: info
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
